version: "3.7"
services:
  app:
    build: "./"
    command: "python manage.py runserver"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: cicdflask
      MYSQL_HOST: db
      RUN_MODE: development
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cicdflask
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - '3316:3306'

volumes:
  db-data:
    driver: local
